package com.flutr.backend.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;

@Document(collection = "org_info")
public class OrgInfo {
    @Id
    private String houseId; // Auto-generated by MongoDB
    private String name;
    private String address;
    private String logoUrl; // URL to the image stored in DigitalOcean Spaces
    private String facilityImgUrl;
    private String adminEmail;
    private List<String> colors; // Array of 3 hex codes
    private String website;
    private SocialMediaLinks socials;
    private String subheading;
    private Otd otd; // Butterfly of the day
    private News news;
    private Boolean statsActive;
    private String timezone;

    public OrgInfo() {}

    public OrgInfo(String houseId, String name, String address, String logoUrl, String facilityImgUrl,
               String adminEmail, List<String> colors, String website, SocialMediaLinks socials,
               String subheading, Otd otd, News news, Boolean statsActive, String timezone) {
        this.houseId = houseId;
        this.name = name;
        this.address = address;
        this.logoUrl = logoUrl;
        this.facilityImgUrl = facilityImgUrl;
        this.adminEmail = adminEmail;
        this.colors = colors;
        this.website = website;
        this.socials = socials;
        this.subheading = subheading;
        this.otd = otd;
        this.news = news;
        this.statsActive = statsActive;
        this.timezone = timezone;
    }


    public String getHouseId() {
        return houseId;
    }

    public void setHouseId(String houseId) {
        this.houseId = houseId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getLogoUrl() {
        return logoUrl;
    }

    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    public String getFacilityImgUrl() {
        return facilityImgUrl;
    }

    public void setFacilityImgUrl(String facilityImgUrl) {
        this.facilityImgUrl = facilityImgUrl;
    }

    public String getAdminEmail() {
        return adminEmail;
    }

    public void setAdminEmail(String adminEmail) {
        this.adminEmail = adminEmail;
    }

    public List<String> getColors() {
        return colors;
    }

    public void setColors(List<String> colors) {
        this.colors = colors;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public SocialMediaLinks getSocials() {
        return socials;
    }

    public void setSocials(SocialMediaLinks socials) {
        this.socials = socials;
    }

    public String getSubheading() {
        return subheading;
    }

    public void setSubheading(String subheading) {
        this.subheading = subheading;
    }

    public Otd getOtd() {
        return otd;
    }

    public void setOtd(Otd otd) {
        this.otd = otd;
    }

    public News getNews() {
        return news;
    }

    public void setNews(News news) {
        this.news = news;
    }

    public Boolean getStatsActive() {
        return statsActive;
    }

    public void setStatsActive(Boolean statsActive) {
        this.statsActive = statsActive;
    }

    public String getTimezone() {
        return timezone;
    }

    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    public static class SocialMediaLinks {
        private boolean instagramActive;
        private String instagramLink;
        private boolean facebookActive;
        private String facebookLink;
        private boolean twitterActive;
        private String twitterLink;
        private boolean youtubeActive;
        private String youtubeLink;

        public SocialMediaLinks() {
        }

        
        public SocialMediaLinks(boolean instagramActive, String instagramLink, boolean facebookActive,
                String facebookLink, boolean twitterActive, String twitterLink, boolean youtubeActive,
                String youtubeLink) {
            this.instagramActive = instagramActive;
            this.instagramLink = instagramLink;
            this.facebookActive = facebookActive;
            this.facebookLink = facebookLink;
            this.twitterActive = twitterActive;
            this.twitterLink = twitterLink;
            this.youtubeActive = youtubeActive;
            this.youtubeLink = youtubeLink;
        }


        public boolean isInstagramActive() {
            return instagramActive;
        }
        public void setInstagramActive(boolean instagramActive) {
            this.instagramActive = instagramActive;
        }
        public String getInstagramLink() {
            return instagramLink;
        }
        public void setInstagramLink(String instagramLink) {
            this.instagramLink = instagramLink;
        }
        public boolean isFacebookActive() {
            return facebookActive;
        }
        public void setFacebookActive(boolean facebookActive) {
            this.facebookActive = facebookActive;
        }
        public String getFacebookLink() {
            return facebookLink;
        }
        public void setFacebookLink(String facebookLink) {
            this.facebookLink = facebookLink;
        }
        public boolean isTwitterActive() {
            return twitterActive;
        }
        public void setTwitterActive(boolean twitterActive) {
            this.twitterActive = twitterActive;
        }
        public String getTwitterLink() {
            return twitterLink;
        }
        public void setTwitterLink(String twitterLink) {
            this.twitterLink = twitterLink;
        }
        public boolean isYoutubeActive() {
            return youtubeActive;
        }
        public void setYoutubeActive(boolean youtubeActive) {
            this.youtubeActive = youtubeActive;
        }
        public String getYoutubeLink() {
            return youtubeLink;
        }
        public void setYoutubeLink(String youtubeLink) {
            this.youtubeLink = youtubeLink;
        }

        
    }

    public static class Otd {
        private boolean active;
        private String buttId;

        public Otd() {
        }

        public Otd(boolean active, String buttId) {
            this.active = active;
            this.buttId = buttId;
        }

        public boolean isActive() {
            return active;
        }
        public void setActive(boolean active) {
            this.active = active;
        }
        public String getButtId() {
            return buttId;
        }
        public void setButtId(String buttId) {
            this.buttId = buttId;
        }

        
    }

    public static class News {
        private boolean active;
        private String newsContent;
        private String newsImageUrl;
        
        public News() {
        }
        public News(boolean active, String newsContent, String newsImageUrl) {
            this.active = active;
            this.newsContent = newsContent;
            this.newsImageUrl = newsImageUrl;
        }
        public boolean isActive() {
            return active;
        }
        public void setActive(boolean active) {
            this.active = active;
        }
        public String getNewsContent() {
            return newsContent;
        }
        public void setNewsContent(String newsContent) {
            this.newsContent = newsContent;
        }
        public String getNewsImageUrl() {
            return newsImageUrl;
        }
        public void setNewsImageUrl(String newsImageUrl) {
            this.newsImageUrl = newsImageUrl;
        }

        
    }
}
